public enum MessageType {
    REGISTER,
    REGISTER_SUCCESS,
    FAILURE,
    EMERGENCY,
    NEEDS_HELP,
    CALL_PATIENT,
    VISIT_PATIENT,
    CALLING_PATIENT_FAILURE,
    CALLING_PATIENT_SUCCESS,
    VISITING_PATIENT_SUCCESS
}
